version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      terraform-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      python-test:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/mcp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      mcp-deps:
        patterns:
          - "*"
