name: Integration Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: TEST_PAT
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements-test.txt requests

      - name: Run unit tests
        run: make test-unit

      - name: Run integration tests
        env:
          TEST_PAT: ${{ secrets.TEST_PAT }}
        run: make test TEST_PAT=$TEST_PAT
